/**
 * The oracle's oracle.
 *
 * `diff-runs.js` decides whether the migration broke anything. Every phase exit
 * in docs/designs/yorick-modernization-differential-cutover.md treats a clean
 * diff as permission to proceed, which makes a silently-broken diff tool worse
 * than no diff tool at all: it converts "we did not check" into "we checked and
 * it was fine".
 *
 * So the tool gets a fixture pair with a deliberately planted regression. The
 * fixtures in test/fixtures/diff-runs/ are REAL Playwright JSON reporter output
 * -- generated by running Playwright against two variants of one spec file --
 * rather than hand-written JSON, so they cannot drift away from the reporter's
 * actual shape when Playwright is upgraded.
 *
 * The planted pair covers every classification the tool can emit:
 *
 *   A  passes in both                      -> same-pass
 *   B  passes then fails                   -> NEW-FAIL   (the planted regression)
 *   C  fails then passes                   -> new-pass
 *   D  present in baseline only            -> removed
 *   E  passes in both, inside a describe    -> same-pass, with a nested key
 *   F  present in candidate only           -> added
 *   G  fails in both                       -> same-fail
 *
 * Run: npm run test:node
 */

'use strict';

const test = require('node:test');
const assert = require('node:assert');
const path = require('path');

const { diffFiles, flatten, specOutcome } = require('../diff-runs');

const FIX = path.join(__dirname, 'fixtures', 'diff-runs');
const BASELINE = path.join(FIX, 'baseline.json');
const CANDIDATE = path.join(FIX, 'candidate.json');

test('finds the planted regression, and only that one', () => {
  const r = diffFiles(BASELINE, CANDIDATE);
  assert.deepStrictEqual(r.newFail, [
    'planted.spec.js :: B is the planted regression',
  ]);
});

test('does not cry wolf when a run is compared against itself', () => {
  const r = diffFiles(BASELINE, BASELINE);
  assert.deepStrictEqual(r.newFail, [], 'identical runs must report no regression');
  assert.deepStrictEqual(r.newPass, []);
  assert.deepStrictEqual(r.added, []);
  assert.deepStrictEqual(r.removed, []);
});

test('classifies every other outcome correctly', () => {
  const r = diffFiles(BASELINE, CANDIDATE);
  assert.deepStrictEqual(r.newPass, ['planted.spec.js :: C gets fixed later']);
  assert.deepStrictEqual(r.sameFail, ['planted.spec.js :: G is broken in both runs']);
  assert.deepStrictEqual(r.added, ['planted.spec.js :: F is new in the candidate']);
  assert.deepStrictEqual(r.removed, [
    'planted.spec.js :: D disappears in the candidate',
  ]);
  assert.deepStrictEqual(r.samePass, [
    'planted.spec.js :: A stays green',
    'planted.spec.js :: nested group :: E stays green inside a describe',
  ]);
});

test('a test inside a describe keeps the describe in its key', () => {
  // Two spec files can hold identically titled describes and tests --
  // creation-vampire.spec.js and creation-werewolf.spec.js are already close to
  // this. If the key collapsed to just the title, those would alias onto each
  // other and a regression in one could be masked by a pass in the other.
  const keys = [...flatten(require(BASELINE)).keys()];
  assert.ok(
    keys.includes('planted.spec.js :: nested group :: E stays green inside a describe'),
    'nested key missing; got:\n  ' + keys.join('\n  ')
  );
  assert.ok(keys.every((k) => k.startsWith('planted.spec.js :: ')), 'every key carries its file');
});

test('--filter narrows the comparison without changing classification', () => {
  const all = diffFiles(BASELINE, CANDIDATE);
  const narrowed = diffFiles(BASELINE, CANDIDATE, 'nested group');
  assert.deepStrictEqual(narrowed.newFail, []);
  assert.deepStrictEqual(narrowed.samePass, [
    'planted.spec.js :: nested group :: E stays green inside a describe',
  ]);
  // The filter must subset, never invent.
  for (const key of Object.keys(narrowed)) {
    for (const entry of narrowed[key]) {
      assert.ok(all[key].includes(entry), key + ' entry appeared only when filtered: ' + entry);
    }
  }
});

test('a filter matching nothing yields no regressions rather than an error', () => {
  const r = diffFiles(BASELINE, CANDIDATE, 'no-such-spec');
  assert.deepStrictEqual(r.newFail, []);
  assert.deepStrictEqual(r.samePass, []);
});

test('a skipped test never registers as a regression', () => {
  assert.deepStrictEqual(
    specOutcome({ ok: true, tests: [{ status: 'skipped' }] }),
    { outcome: 'skipped', flaky: false }
  );
});

test('a flaky pass is a pass, but is surfaced', () => {
  const out = specOutcome({ ok: true, tests: [{ status: 'flaky' }] });
  assert.strictEqual(out.outcome, 'passed');
  assert.strictEqual(out.flaky, true, 'flakiness must stay visible -- it is the main diff-noise source');
});
