/**
 * Each jQuery Mobile page's heading.
 *
 * GENERATED by web/scripts/generate-page-titles.mjs from public/index.html.
 * Do not edit by hand; run `npm run generate:routes` instead.
 *
 * The header shows this, and the footer navbar marks the tab whose label
 * matches it -- both behaviours from public/scripts/app/main.js. A null means
 * the page declared no `data-title`, and the legacy header would have shown
 * an empty heading.
 */

export const pageTitles: Record<string, string | null> = {
  "splashscreen": "Yorick Splash Screen",
  "login": "Log In",
  "signup": "Sign Up",
  "about": "About",
  "privacy": "Privacy Policy",
  "player-options": "Player Options",
  "administration": "Administration",
  "troupe-new": "New Troupe",
  "troupes-list": "Troupes",
  "character-pick-troupe-to-leave": "Leave Troupe",
  "character-pick-troupe-to-join": "Join Troupe",
  "character-pick-troupe-to-show": "Show Troupe",
  "troupe": "Troupe",
  "troupe-add-staff": "Add Staff",
  "troupe-edit-staff": "Edit Staff",
  "character": "Character",
  "characters-all": "Characters",
  "troupe-characters-all": "Troupe Characters",
  "troupe-summarize-characters-all": "Troupe Characters",
  "troupe-select-to-print-characters-all": "Troupe Characters",
  "troupe-print-characters-all": "Print Troupe Characters",
  "administration-descriptions": "Descriptions",
  "simpletraitcategory-all": "SimpleTraitCategoryAll",
  "simpletrait-change": "SimpleTraitChange",
  "victims-all": "VictimsAll",
  "experience-notations-all": "Experience Notations",
  "experience-notation-change": null,
  "animals": "Animals",
  "colors": "Colors",
  "vehicles": "Vehicles",
  "character-new": "New Character",
  "simpletrait-new": "New Simple Trait",
  "character-create-simpletrait-new": "New Simple Trait",
  "simpletext-new": "New Simple Text",
  "character-costs": "Character Costs",
  "printable-sheet": "Printable Sheet",
  "character-create": "Create Character",
  "simpletrait-specialization": "Simple Trait Specialization",
  "simpletrait-new-specialization": "Simple Trait Specialization",
  "character-log": "Character Log",
  "character-history": "Character History",
  "character-approval": "Character Approval",
  "character-rename": "Rename Character",
  "user-settings-profile": "Profile",
  "administration-user-view": "User View",
  "administration-user-patronages-view": "Patronages",
  "administration-patronages-view": "Patronages",
  "administration-patronages-view-csv": "Patronages",
  "administration-patronage-view": "Patronage",
  "user-reset-password": "Reset Password",
  "character-portrait": "Profile",
  "troupe-portrait": "Profile",
  "troupe-character-relationships-network": "Relationships Network",
  "character-delete": "Delete Character",
  "character-print-no-approval": "Print Approval",
  "extended-print-text": "Additional Printed Text",
  "long-text": "Long Text",
  "referendums-list": "Referendums",
  "referendum": "Referendum",
};

/** The heading for a page id, or an empty string if it has none. */
export function titleFor(pageId: string): string {
  return pageTitles[pageId] ?? '';
}
