/**
 * The legacy route table.
 *
 * GENERATED by web/scripts/generate-route-table.mjs from
 * public/scripts/app/routers/mobileRouter.js. Do not edit by hand; run
 * `npm run generate:routes` instead.
 *
 * Order is significant: Backbone tries routes in declaration order and takes
 * the first match, which is why `troupe/new` appears before `troupe/:id`.
 * The React router keeps that ordering and that first-match rule.
 *
 * `handler` is the legacy method name on mobileRouter. It is the key screens
 * register themselves under, so every entry here names the thing that has to
 * exist for the URL to work -- and the ones with no screen yet are exactly the
 * migration's remaining work.
 */

export interface RouteEntry {
  pattern: string;
  handler: string;
}

export const routeTable: RouteEntry[] = [
  { pattern: "", handler: "home" },
  { pattern: "start", handler: "home" },
  { pattern: "about", handler: "about" },
  { pattern: "privacy", handler: "privacy_policy" },
  { pattern: "logout", handler: "logout" },
  { pattern: "signup", handler: "signup" },
  { pattern: "reset", handler: "resetpassword" },
  { pattern: "profile", handler: "profile" },
  { pattern: "patronage/:id", handler: "a_patronage" }, // When #category? is on the url, the category method is called
  { pattern: "category?:type", handler: "category" },
  { pattern: "victims?:type", handler: "victims" },
  { pattern: "characters?:type", handler: "characters" },
  { pattern: "character?:id", handler: "character" },
  { pattern: "simpletraits/:category/:cid/:type", handler: "simpletraits" },
  { pattern: "simpletrait/:category/:cid/:bid", handler: "simpletrait" },
  { pattern: "simpletrait/specialize/:category/:cid/:bid", handler: "simpletraitspecialize" },
  { pattern: "simpletrait/spacer/:category/:cid/:name/:value/:free_value/new", handler: "simpletraitnew" },
  { pattern: "simpletrait/specialize/:category/:cid/:name/:value/:free_value/new", handler: "simpletrait_new_specialize" },
  { pattern: "simpletext/:category/:target/:cid/pick", handler: "simpletextpick" },
  { pattern: "simpletext/:category/:target/:cid/unpick", handler: "simpletextunpick" },
  { pattern: "charactercreate/:cid", handler: "charactercreate" },
  { pattern: "charactercreate/simpletraits/:category/:cid/pick/:i", handler: "charactercreatepicksimpletrait" },
  { pattern: "charactercreate/simpletraits/:category/:cid/unpick/:stid/:i", handler: "charactercreateunpicksimpletrait" },
  { pattern: "charactercreate/simpletraits/:category/:cid/specialize/:stid/:i", handler: "charactercreatespecializesimpletrait" },
  { pattern: "charactercreate/simpletext/:category/:target/:cid/pick", handler: "charactercreatepicksimpletext" },
  { pattern: "charactercreate/simpletext/:category/:target/:cid/unpick", handler: "charactercreateunpicksimpletext" },
  { pattern: "charactercreate/complete/:cid", handler: "charactercreatecomplete" },
  { pattern: "characternew", handler: "characternew" },
  { pattern: "character/:cid/print", handler: "characterprint" },
  { pattern: "character/:cid/costs", handler: "charactercosts" },
  { pattern: "character/:cid/log/:start/:changeBy", handler: "characterlog" },
  { pattern: "character/:cid/history/:id", handler: "characterhistory" },
  { pattern: "character/:cid/portrait", handler: "characterportrait" },
  { pattern: "character/:cid/delete", handler: "characterdelete" },
  { pattern: "character/:cid/troupes", handler: "character_list_troupes" },
  { pattern: "character/:cid/troupes/leave", handler: "character_pick_troupe_to_leave" },
  { pattern: "character/:cid/troupes/join", handler: "character_pick_troupe_to_join" },
  { pattern: "character/:cid/troupe/:tid/join", handler: "character_join_troupe" },
  { pattern: "character/:cid/troupe/:tid/leave", handler: "character_leave_troupe" },
  { pattern: "character/:cid/troupe/:tid/show", handler: "character_show_troupe" },
  { pattern: "character/:cid/approval", handler: "characterapproval" },
  { pattern: "character/:cid/rename", handler: "characterrename" },
  { pattern: "character/:cid/approved", handler: "character_show_approved" },
  { pattern: "character/:cid/extendedprinttext", handler: "character_extended_print_text" },
  { pattern: "character/:cid/backgroundlt", handler: "character_background_long_text" },
  { pattern: "character/:cid/noteslt", handler: "character_notes_long_text" },
  { pattern: "character/:cid/experience/:start/:changeBy", handler: "characterexperience" },
  { pattern: "troupe/new", handler: "troupenew" },
  { pattern: "troupes", handler: "troupes" },
  { pattern: "troupe/:id", handler: "troupe" },
  { pattern: "troupe/:id/staff/add", handler: "troupeaddstaff" },
  { pattern: "troupe/:id/staff/edit/:uid", handler: "troupeeditstaff" },
  { pattern: "troupe/:id/characters/:type", handler: "troupecharacters" },
  { pattern: "troupe/:id/characters/summarize/:type", handler: "troupesummarizecharacters" },
  { pattern: "troupe/:id/characters/selecttoprint/:type", handler: "troupe_select_to_print_characters" },
  { pattern: "troupe/:id/characters/print/:type", handler: "troupe_print_characters" },
  { pattern: "troupe/:id/characters/relationships/network", handler: "troupe_relationship_network" },
  { pattern: "troupe/:id/character/:cid", handler: "troupe_character" },
  { pattern: "troupe/:id/portrait", handler: "troupe_portrait" },
  { pattern: "administration", handler: "administration" },
  { pattern: "administration/characters/all", handler: "administration_characters_all" },
  { pattern: "administration/characters/summarize", handler: "administration_characters_summarize" },
  { pattern: "administration/character/:id", handler: "administration_character" },
  { pattern: "administration/users/all", handler: "administration_users" },
  { pattern: "administration/user/:id", handler: "administration_user" },
  { pattern: "administration/patronages/user/:id", handler: "administration_user_patronages" },
  { pattern: "administration/patronages", handler: "administration_patronages" },
  { pattern: "administration/patronagescsv", handler: "administration_patronages_csv" },
  { pattern: "administration/patronage/:id", handler: "administration_patronage" },
  { pattern: "administration/patronages/new", handler: "administration_patronage_new" },
  { pattern: "administration/patronages/new/:userid", handler: "administration_patronage_new" },
  { pattern: "administration/descriptions", handler: "administration_descriptions" },
  { pattern: "administration/bnsctdbs_kith_rules", handler: "administration_bnsctdbs_kith_rules" },
  { pattern: "administration/bnsmetv1_clan_rules", handler: "administration_bnsmetv1_clan_rules" },
  { pattern: "administration/bnsmetv1_elder_discipline_rules", handler: "administration_bnsmetv1_elder_discipline_rules" },
  { pattern: "administration/bnsmetv1_technique_rules", handler: "administration_bnsmetv1_technique_rules" },
  { pattern: "administration/bnsmetv1_ritual_rules", handler: "administration_bnsmetv1_ritual_rules" }, // Referendums
  { pattern: "referendums", handler: "referendums" }, // Listing of active referendums
  { pattern: "referendum/:id", handler: "referendum" }, // Description of an individual referendum with the ballot questions
  { pattern: "administration/referendums", handler: "administration_referendums" }, // Listing of active referendums
  { pattern: "administration/referendum/:id", handler: "administration_referendum" }, // Admin view of a referendum
];
