/**
 * What each legacy route handler renders.
 *
 * GENERATED by web/scripts/generate-screen-map.mjs from
 * public/scripts/app/routers/mobileRouter.js. Do not edit by hand; run
 * `npm run generate:routes` instead.
 *
 * `pageId` is the jQuery Mobile page the handler transitions to. The React
 * screens keep these ids, because `.ui-page-active` plus the id is how the
 * Playwright suite knows where it is.
 *
 * `alsoUses` lists further pages a handler can land on -- e.g.
 * `character_show_approved` shows the printable sheet or the "not approved"
 * page depending on the character.
 */

export interface ScreenInfo {
  pageId: string | null;
  args: string[];
  alsoUses?: string[];
}

export const screenMap: Record<string, ScreenInfo> = {
  home: { pageId: "player-options", args: [] },
  logout: { pageId: null, args: [] },
  signup: { pageId: "signup", args: [] },
  about: { pageId: "about", args: [] },
  privacy_policy: { pageId: "privacy", args: [] },
  resetpassword: { pageId: "user-reset-password", args: [] },
  profile: { pageId: "user-settings-profile", args: [] },
  a_patronage: { pageId: "administration-patronage-view", args: ["id"] },
  charactercosts: { pageId: "character-costs", args: ["cid"] },
  characterlog: { pageId: "character-log", args: ["cid","start","changeBy"] },
  characterexperience: { pageId: "experience-notations-all", args: ["cid","start","changeBy"] },
  characterhistory: { pageId: "character-history", args: ["cid","id"] },
  characterapproval: { pageId: "character-approval", args: ["cid"] },
  character_show_approved: { pageId: "character-print-no-approval", args: ["cid"], alsoUses: ["printable-sheet"] },
  characterrename: { pageId: "character-rename", args: ["cid"] },
  characterprint: { pageId: "printable-sheet", args: ["cid"] },
  characternew: { pageId: "character-new", args: [] },
  charactercreate: { pageId: "character-create", args: ["cid"] },
  charactercreatepicksimpletrait: { pageId: "character-create-simpletrait-new", args: ["category","cid","i"] },
  charactercreatespecializesimpletrait: { pageId: "simpletrait-specialization", args: ["category","cid","stid","i"] },
  charactercreateunpicksimpletrait: { pageId: null, args: ["category","cid","stid","i"] },
  charactercreatepicksimpletext: { pageId: "simpletext-new", args: ["category","target","cid"] },
  charactercreateunpicksimpletext: { pageId: null, args: ["category","target","cid"] },
  charactercreatecomplete: { pageId: null, args: ["cid"] },
  characterportrait: { pageId: "character-portrait", args: ["cid"] },
  character_extended_print_text: { pageId: "extended-print-text", args: ["cid"] },
  character_background_long_text: { pageId: "long-text", args: ["cid"] },
  character_notes_long_text: { pageId: "long-text", args: ["cid"] },
  character: { pageId: null, args: ["id"] },
  troupe_character: { pageId: null, args: ["id","cid"] },
  administration_character: { pageId: null, args: ["id"] },
  administration_users: { pageId: "troupe-add-staff", args: [] },
  administration_user: { pageId: "administration-user-view", args: ["id"] },
  administration_user_patronages: { pageId: "administration-user-patronages-view", args: ["id"] },
  administration_patronages: { pageId: "administration-patronages-view", args: [] },
  administration_patronages_csv: { pageId: "administration-patronages-view-csv", args: [] },
  administration_patronage: { pageId: "administration-patronage-view", args: ["id"] },
  administration_patronage_new: { pageId: "administration-patronage-view", args: ["userid"] },
  administration_descriptions: { pageId: "administration-descriptions", args: [] },
  administration_bnsctdbs_kith_rules: { pageId: "administration-descriptions", args: [] },
  administration_bnsmetv1_clan_rules: { pageId: "administration-descriptions", args: [] },
  administration_bnsmetv1_elder_discipline_rules: { pageId: "administration-descriptions", args: [] },
  administration_bnsmetv1_technique_rules: { pageId: "administration-descriptions", args: [] },
  administration_bnsmetv1_ritual_rules: { pageId: "administration-descriptions", args: [] },
  characterdelete: { pageId: "character-delete", args: ["cid"] },
  characters: { pageId: "characters-all", args: ["type"] },
  simpletrait: { pageId: "simpletrait-change", args: ["category","cid","bid"] },
  simpletraitspecialize: { pageId: "simpletrait-specialization", args: ["category","cid","bid"] },
  simpletraitnew: { pageId: "simpletrait-change", args: ["category","cid","name","value","free_value"] },
  simpletrait_new_specialize: { pageId: "simpletrait-new-specialization", args: ["category","cid","name","value","free_value"] },
  simpletextpick: { pageId: "simpletext-new", args: ["category","target","cid"] },
  simpletextunpick: { pageId: null, args: ["category","target","cid"] },
  simpletraits: { pageId: "simpletraitcategory-all", args: ["category","cid","type"], alsoUses: ["simpletrait-new"] },
  victims: { pageId: "victims-all", args: ["type"] },
  category: { pageId: null, args: ["type"] },
  character_list_troupes: { pageId: "character-pick-troupe-to-show", args: ["cid"] },
  character_pick_troupe_to_leave: { pageId: "character-pick-troupe-to-leave", args: ["cid"] },
  character_pick_troupe_to_join: { pageId: "character-pick-troupe-to-join", args: ["cid"] },
  character_show_troupe: { pageId: "troupe", args: ["cid","tid"] },
  character_join_troupe: { pageId: "troupe", args: ["cid","tid"] },
  character_leave_troupe: { pageId: null, args: ["cid","tid"] },
  troupecharacters: { pageId: "troupe-characters-all", args: ["id","type"] },
  troupesummarizecharacters: { pageId: "troupe-summarize-characters-all", args: ["id","type"] },
  troupe_select_to_print_characters: { pageId: "troupe-select-to-print-characters-all", args: ["id","type"] },
  troupe_print_characters: { pageId: "troupe-print-characters-all", args: ["id","type"] },
  troupe_portrait: { pageId: "troupe-portrait", args: ["id"] },
  troupe_relationship_network: { pageId: "troupe-character-relationships-network", args: ["id"] },
  troupeeditstaff: { pageId: "troupe-edit-staff", args: ["id","uid"] },
  troupeaddstaff: { pageId: "troupe-add-staff", args: ["id"] },
  troupe: { pageId: "troupe", args: ["id"] },
  troupes: { pageId: "troupes-list", args: [] },
  troupenew: { pageId: "troupe-new", args: [] },
  administration: { pageId: "administration", args: [] },
  administration_characters_all: { pageId: "characters-all", args: [] },
  administration_characters_summarize: { pageId: "troupe-summarize-characters-all", args: [] },
};
