/**
 * The three venues' static data.
 *
 * GENERATED DATA — column names, pool seeds, pricing rules. All strings are live
 * Parse column names or values already written to server rows. They are typed as
 * plain `string` deliberately: narrowing them to a union would invite a future
 * edit that "cleans up" a name and silently orphans a column.
 *
 * Source of truth: the venue model files in `public/scripts/app/models/` and the
 * cost engine files in `client/src/domain/rules/`. Run the generator to refresh:
 *   npm run generate:venues
 *
 * ## Fields
 *
 * `categories` — ALL_SIMPLETRAIT_CATEGORIES, positionally significant.
 * `textAttributes` — TEXT_ATTRIBUTES paired with TEXT_ATTRIBUTES_PRETTY_NAMES.
 * `sumCreationCategories` — categories whose creation pool is a sum, not a count.
 * `freeCategories` — categories that genuinely cost nothing (FREE_CATEGORIES from
 *   the cost engine allowlist). Unlisted categories return undefined (refused).
 * `creationSeed` — exact pool seed for a new creation row.
 * `creationListCategories` — categories that can hold creation picks.
 * `totalCostCategories` — categories calculate_total_cost walks.
 * `getCharacterIncludes` — pointer columns fetched with get_character.
 * `startingTraits` — traits every new character starts with.
 * `troupeMembershipThrottled` — whether Vampire.js:367 throttles this venue.
 * `typeAttribute` — literal written to the type column, or undefined (Vampire).
 */

import type {
  CreationSeed,
  StartingTrait,
  TextAttribute,
  TraitCategory,
  VenueData,
} from './types'

export { type TraitCategory, type TextAttribute }

export const venueData: Record<'Vampire' | 'Werewolf' | 'ChangelingBetaSlice', VenueData> = {
  Vampire: {
    categories: [
      { key: "attributes", prettyName: "Attributes", group: "Attributes" },
      { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
      { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
      { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
      { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
      { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
      { key: "skills", prettyName: "Skills", group: "Skills" },
      { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
      { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
      { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
      { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
      { key: "disciplines", prettyName: "Disciplines", group: "Disciplines" },
      { key: "techniques", prettyName: "Techniques", group: "Disciplines" },
      { key: "elder_disciplines", prettyName: "Elder Disciplines", group: "Disciplines" },
      { key: "luminary_disciplines", prettyName: "Luminary Disciplines", group: "Disciplines" },
      { key: "rituals", prettyName: "Rituals", group: "Disciplines" },
      { key: "extra_in_clan_disciplines", prettyName: "Extra In Clan Disciplines", group: "Disciplines" },
      { key: "paths", prettyName: "Path of Enlightenment/Humanity", group: "Morality" },
      { key: "backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
      { key: "haven_specializations", prettyName: "Haven Specializations", group: "Backgrounds" },
      { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
      { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
      { key: "sabbat_rituals", prettyName: "Sabbat Ritae", group: "Backgrounds" },
      { key: "vampiric_texts", prettyName: "Vampiric Texts", group: "Backgrounds" },
      { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
      { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
      { key: "status_traits", prettyName: "Sect Status", group: "Backgrounds" },
      { key: "merits", prettyName: "Merits", group: "Merits and Flaws" },
      { key: "flaws", prettyName: "Flaws", group: "Merits and Flaws" },
    ],
    textAttributes: [
      { key: "clan", label: "Clan" },
      { key: "archetype", label: "Archetype" },
      { key: "sect", label: "Sect" },
      { key: "faction", label: "Faction" },
      { key: "title", label: "Title" },
      { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["merits","flaws"],
    freeCategories: [
      "focus_physicals",
      "focus_mentals",
      "focus_socials",
      "health_levels",
      "willpower_sources",
      "lore_specializations",
      "academics_specializations",
      "drive_specializations",
      "linguistics_specializations",
      "extra_in_clan_disciplines",
      "haven_specializations",
      "contacts_specializations",
      "allies_specializations",
      "sabbat_rituals",
      "vampiric_texts",
      "influence_elite_specializations",
      "influence_underworld_specializations",
      "status_traits",
    ],
    creationSeed: {
      completed: false,
      concept: false,
      archetype: false,
      clan: false,
      attributes: false,
      focuses: false,
      skills_4_remaining: 1,
      skills_3_remaining: 2,
      skills_2_remaining: 3,
      skills_1_remaining: 4,
      backgrounds_3_remaining: 1,
      backgrounds_2_remaining: 1,
      backgrounds_1_remaining: 1,
      disciplines_2_remaining: 1,
      disciplines_1_remaining: 2,
      attributes_7_remaining: 1,
      attributes_5_remaining: 1,
      attributes_3_remaining: 1,
      focus_mentals_1_remaining: 1,
      focus_socials_1_remaining: 1,
      focus_physicals_1_remaining: 1,
      merits_0_remaining: 7,
      flaws_0_remaining: 7,
      phase_1_finished: false,
      initial_xp: 30,
      phase_2_finished: false,
    } as CreationSeed,
    creationListCategories: [
      "flaws",
      "merits",
      "focus_mentals",
      "focus_physicals",
      "focus_socials",
      "attributes",
      "skills",
      "backgrounds",
      "disciplines",
    ],
    totalCostCategories: [
      "skills",
      "backgrounds",
      "disciplines",
      "attributes",
      "merits",
      "rituals",
      "techniques",
      "elder_disciplines",
      "luminary_disciplines",
    ],
    getCharacterIncludes: ["backgrounds", "extra_in_clan_disciplines"],
    startingTraits: [
      { name: "Humanity", value: 5, category: "paths", free_value: 5 },
      { name: "Healthy", value: 3, category: "health_levels", free_value: 3 },
      { name: "Injured", value: 3, category: "health_levels", free_value: 3 },
      { name: "Incapacitated", value: 3, category: "health_levels", free_value: 3 },
      { name: "Willpower", value: 6, category: "willpower_sources", free_value: 6 },
    ] as StartingTrait[],
    troupeMembershipThrottled: true,
    typeAttribute: undefined,
  },
  Werewolf: {
    categories: [
      { key: "attributes", prettyName: "Attributes", group: "Attributes" },
      { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
      { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
      { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
      { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
      { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
      { key: "wta_gnosis_sources", prettyName: "Gnosis", group: "Expended" },
      { key: "skills", prettyName: "Skills", group: "Skills" },
      { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
      { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
      { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
      { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
      { key: "wta_gifts", prettyName: "Gifts", group: "Gifts" },
      { key: "extra_affinity_links", prettyName: "Extra Affinities", group: "Gifts" },
      { key: "wta_backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
      { key: "wta_territory_specializations", prettyName: "Territory Specializations", group: "Backgrounds" },
      { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
      { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
      { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
      { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
      { key: "wta_rites", prettyName: "Rites", group: "Backgrounds" },
      { key: "wta_monikers", prettyName: "Monikers", group: "Backgrounds" },
      { key: "wta_merits", prettyName: "Merits", group: "Merits and Flaws" },
      { key: "wta_flaws", prettyName: "Flaws", group: "Merits and Flaws" },
      { key: "wta_totem_bonus_traits", prettyName: "Totem Bonuses", group: "Pack" },
    ],
    textAttributes: [
      { key: "archetype", label: "Archetype" },
      { key: "archetype_2", label: "Second Archetype" },
      { key: "wta_breed", label: "Breed" },
      { key: "wta_auspice", label: "Auspice" },
      { key: "wta_tribe", label: "Tribe" },
      { key: "wta_camp", label: "Camp" },
      { key: "wta_faction", label: "Faction" },
      { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["wta_merits","wta_flaws"],
    freeCategories: [
      "focus_physicals",
      "focus_mentals",
      "focus_socials",
      "health_levels",
      "willpower_sources",
      "wta_gnosis_sources",
      "lore_specializations",
      "academics_specializations",
      "drive_specializations",
      "linguistics_specializations",
      "extra_affinity_links",
      "wta_territory_specializations",
      "contacts_specializations",
      "allies_specializations",
      "influence_elite_specializations",
      "influence_underworld_specializations",
      "wta_monikers",
      "wta_totem_bonus_traits",
    ],
    creationSeed: {
      completed: false,
      concept: false,
      archetype: false,
      clan: false,
      attributes: false,
      focuses: false,
      skills_4_remaining: 1,
      skills_3_remaining: 2,
      skills_2_remaining: 3,
      skills_1_remaining: 4,
      wta_backgrounds_3_remaining: 1,
      wta_backgrounds_2_remaining: 1,
      wta_backgrounds_1_remaining: 1,
      wta_gifts_1_remaining: 3,
      attributes_7_remaining: 1,
      attributes_5_remaining: 1,
      attributes_3_remaining: 1,
      focus_mentals_1_remaining: 1,
      focus_socials_1_remaining: 1,
      focus_physicals_1_remaining: 1,
      wta_merits_0_remaining: 7,
      wta_flaws_0_remaining: 7,
      phase_1_finished: false,
      initial_xp: 30,
      phase_2_finished: false,
    } as CreationSeed,
    creationListCategories: [
      "wta_flaws",
      "wta_merits",
      "focus_mentals",
      "focus_physicals",
      "focus_socials",
      "attributes",
      "skills",
      "wta_backgrounds",
      "wta_gifts",
    ],
    totalCostCategories: [
      "skills",
      "wta_backgrounds",
      "wta_gifts",
      "attributes",
      "wta_merits",
    ],
    getCharacterIncludes: ["wta_backgrounds", "extra_affinity_links"],
    startingTraits: [
      { name: "Healthy", value: 3, category: "health_levels", free_value: 3 },
      { name: "Injured", value: 3, category: "health_levels", free_value: 3 },
      { name: "Incapacitated", value: 3, category: "health_levels", free_value: 3 },
      { name: "Willpower", value: 6, category: "willpower_sources", free_value: 6 },
      { name: "Gnosis", value: 10, category: "wta_gnosis_sources", free_value: 6 },
    ] as StartingTrait[],
    troupeMembershipThrottled: false,
    typeAttribute: "Werewolf",
  },
  ChangelingBetaSlice: {
    categories: [
      { key: "attributes", prettyName: "Attributes", group: "Attributes" },
      { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
      { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
      { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
      { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
      { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
      { key: "skills", prettyName: "Skills", group: "Skills" },
      { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
      { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
      { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
      { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
      { key: "ctdbs_arts", prettyName: "Arts", group: "Arts" },
      { key: "ctdbs_arts_affinities_links", prettyName: "Arts Affinities", group: "Arts" },
      { key: "ctdbs_realms", prettyName: "Realms", group: "Arts" },
      { key: "ctdbs_backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
      { key: "ctdbs_holdings_specializations", prettyName: "Holdings Specializations", group: "Backgrounds" },
      { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
      { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
      { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
      { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
      { key: "ctdbs_merits", prettyName: "Merits", group: "Merits and Flaws" },
      { key: "ctdbs_flaws", prettyName: "Flaws", group: "Merits and Flaws" },
    ],
    textAttributes: [
      { key: "archetype", label: "Archetype" },
      { key: "ctdbs_kith", label: "Kith" },
      { key: "ctdbs_fealty_court", label: "Court" },
      { key: "ctdbs_noble_house", label: "House" },
      { key: "ctdbs_kith_group_type", label: "Group" },
      { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["ctdbs_merits","ctdbs_flaws"],
    freeCategories: [
      "focus_physicals",
      "focus_mentals",
      "focus_socials",
      "health_levels",
      "willpower_sources",
      "lore_specializations",
      "academics_specializations",
      "drive_specializations",
      "linguistics_specializations",
      "ctdbs_arts_affinities_links",
      "ctdbs_holdings_specializations",
      "contacts_specializations",
      "allies_specializations",
      "influence_elite_specializations",
      "influence_underworld_specializations",
    ],
    creationSeed: {
      completed: false,
      concept: false,
      archetype: false,
      clan: false,
      attributes: false,
      focuses: false,
      skills_4_remaining: 1,
      skills_3_remaining: 2,
      skills_2_remaining: 3,
      skills_1_remaining: 4,
      ctdbs_backgrounds_3_remaining: 1,
      ctdbs_backgrounds_2_remaining: 1,
      ctdbs_backgrounds_1_remaining: 1,
      attributes_7_remaining: 1,
      attributes_5_remaining: 1,
      attributes_3_remaining: 1,
      ctdbs_arts_1_remaining: 3,
      focus_mentals_1_remaining: 1,
      focus_socials_1_remaining: 1,
      focus_physicals_1_remaining: 1,
      ctdbs_merits_0_remaining: 7,
      ctdbs_flaws_0_remaining: 7,
      phase_1_finished: false,
      initial_xp: 30,
      phase_2_finished: false,
    } as CreationSeed,
    creationListCategories: [
      "ctdbs_flaws",
      "ctdbs_merits",
      "focus_mentals",
      "focus_physicals",
      "focus_socials",
      "attributes",
      "skills",
      "ctdbs_backgrounds",
      "ctdbs_arts",
    ],
    totalCostCategories: [
      "skills",
      "ctdbs_backgrounds",
      "ctdbs_arts",
      "attributes",
      "ctdbs_merits",
    ],
    getCharacterIncludes: [
      "ctdbs_backgrounds",
      "ctdbs_arts_affinities_links",
      "ctdbs_realms",
    ],
    startingTraits: [
      { name: "Healthy", value: 3, category: "health_levels", free_value: 3 },
      { name: "Injured", value: 3, category: "health_levels", free_value: 3 },
      { name: "Incapacitated", value: 3, category: "health_levels", free_value: 3 },
      { name: "Willpower", value: 6, category: "willpower_sources", free_value: 6 },
    ] as StartingTrait[],
    troupeMembershipThrottled: false,
    typeAttribute: "ChangelingBetaSlice",
  },
}
