/**
 * The three venues' static tables.
 *
 * GENERATED by web/scripts/generate-venue-data.mjs from
 * public/scripts/app/models/{Vampire,Werewolf,ChangelingBetaSlice}.js.
 * Do not edit by hand; run `npm run generate:venues` instead.
 *
 * `categories` is ALL_SIMPLETRAIT_CATEGORIES, whose rows the legacy code reads
 * positionally as [key, prettyName, groupName]. Order is significant: it is the
 * order sections appear on a character sheet.
 *
 * `textAttributes` pairs TEXT_ATTRIBUTES with TEXT_ATTRIBUTES_PRETTY_NAMES,
 * which the legacy code keeps as two parallel arrays indexed together. Two of
 * those labels are written as `function (character) { return "..."; }` rather
 * than as strings -- the vampire's faction and the changeling's kith group
 * type. Both ignore the character and return a constant, so they are flattened
 * to strings here. The generator checks that: if either ever starts depending
 * on the character, it fails rather than silently freezing the wrong label.
 *
 * `sumCreationCategories` is SUM_CREATION_CATEGORIES -- the categories whose
 * creation pool is spent as a sum of trait values rather than as a count of
 * picks. Everywhere else a pick costs one slot; in these, a 3-point merit costs
 * three.
 */

export interface TraitCategory {
  /** The attribute name on the character, e.g. "disciplines". */
  key: string;
  /** The heading shown for it, e.g. "Disciplines". */
  prettyName: string;
  /** The sheet section it belongs to, e.g. "Attributes". */
  group: string;
}

export interface TextAttribute {
  key: string;
  label: string;
}

export interface VenueData {
  categories: TraitCategory[];
  textAttributes: TextAttribute[];
  sumCreationCategories: string[];
}

export const venueData: Record<'Vampire' | 'Werewolf' | 'ChangelingBetaSlice', VenueData> = {
  Vampire: {
    categories: [
    { key: "attributes", prettyName: "Attributes", group: "Attributes" },
    { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
    { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
    { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
    { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
    { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
    { key: "skills", prettyName: "Skills", group: "Skills" },
    { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
    { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
    { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
    { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
    { key: "disciplines", prettyName: "Disciplines", group: "Disciplines" },
    { key: "techniques", prettyName: "Techniques", group: "Disciplines" },
    { key: "elder_disciplines", prettyName: "Elder Disciplines", group: "Disciplines" },
    { key: "luminary_disciplines", prettyName: "Luminary Disciplines", group: "Disciplines" },
    { key: "rituals", prettyName: "Rituals", group: "Disciplines" },
    { key: "extra_in_clan_disciplines", prettyName: "Extra In Clan Disciplines", group: "Disciplines" },
    { key: "paths", prettyName: "Path of Enlightenment/Humanity", group: "Morality" },
    { key: "backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
    { key: "haven_specializations", prettyName: "Haven Specializations", group: "Backgrounds" },
    { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
    { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
    { key: "sabbat_rituals", prettyName: "Sabbat Ritae", group: "Backgrounds" },
    { key: "vampiric_texts", prettyName: "Vampiric Texts", group: "Backgrounds" },
    { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
    { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
    { key: "status_traits", prettyName: "Sect Status", group: "Backgrounds" },
    { key: "merits", prettyName: "Merits", group: "Merits and Flaws" },
    { key: "flaws", prettyName: "Flaws", group: "Merits and Flaws" },
    ],
    textAttributes: [
    { key: "clan", label: "Clan" },
    { key: "archetype", label: "Archetype" },
    { key: "sect", label: "Sect" },
    { key: "faction", label: "Faction" },
    { key: "title", label: "Title" },
    { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["merits","flaws"],
  },
  Werewolf: {
    categories: [
    { key: "attributes", prettyName: "Attributes", group: "Attributes" },
    { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
    { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
    { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
    { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
    { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
    { key: "wta_gnosis_sources", prettyName: "Gnosis", group: "Expended" },
    { key: "skills", prettyName: "Skills", group: "Skills" },
    { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
    { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
    { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
    { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
    { key: "wta_gifts", prettyName: "Gifts", group: "Gifts" },
    { key: "extra_affinity_links", prettyName: "Extra Affinities", group: "Gifts" },
    { key: "wta_backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
    { key: "wta_territory_specializations", prettyName: "Territory Specializations", group: "Backgrounds" },
    { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
    { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
    { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
    { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
    { key: "wta_rites", prettyName: "Rites", group: "Backgrounds" },
    { key: "wta_monikers", prettyName: "Monikers", group: "Backgrounds" },
    { key: "wta_merits", prettyName: "Merits", group: "Merits and Flaws" },
    { key: "wta_flaws", prettyName: "Flaws", group: "Merits and Flaws" },
    { key: "wta_totem_bonus_traits", prettyName: "Totem Bonuses", group: "Pack" },
    ],
    textAttributes: [
    { key: "archetype", label: "Archetype" },
    { key: "archetype_2", label: "Second Archetype" },
    { key: "wta_breed", label: "Breed" },
    { key: "wta_auspice", label: "Auspice" },
    { key: "wta_tribe", label: "Tribe" },
    { key: "wta_camp", label: "Camp" },
    { key: "wta_faction", label: "Faction" },
    { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["wta_merits","wta_flaws"],
  },
  ChangelingBetaSlice: {
    categories: [
    { key: "attributes", prettyName: "Attributes", group: "Attributes" },
    { key: "focus_physicals", prettyName: "Physical Focus", group: "Attributes" },
    { key: "focus_mentals", prettyName: "Mental Focus", group: "Attributes" },
    { key: "focus_socials", prettyName: "Social Focus", group: "Attributes" },
    { key: "health_levels", prettyName: "Health Levels", group: "Expended" },
    { key: "willpower_sources", prettyName: "Willpower", group: "Expended" },
    { key: "skills", prettyName: "Skills", group: "Skills" },
    { key: "lore_specializations", prettyName: "Lore Specializations", group: "Skills" },
    { key: "academics_specializations", prettyName: "Academics Specializations", group: "Skills" },
    { key: "drive_specializations", prettyName: "Drive Specializations", group: "Skills" },
    { key: "linguistics_specializations", prettyName: "Languages", group: "Skills" },
    { key: "ctdbs_arts", prettyName: "Arts", group: "Arts" },
    { key: "ctdbs_arts_affinities_links", prettyName: "Arts Affinities", group: "Arts" },
    { key: "ctdbs_realms", prettyName: "Realms", group: "Arts" },
    { key: "ctdbs_backgrounds", prettyName: "Backgrounds", group: "Backgrounds" },
    { key: "ctdbs_holdings_specializations", prettyName: "Holdings Specializations", group: "Backgrounds" },
    { key: "contacts_specializations", prettyName: "Contacts Specializations", group: "Backgrounds" },
    { key: "allies_specializations", prettyName: "Allies Specializations", group: "Backgrounds" },
    { key: "influence_elite_specializations", prettyName: "Influence: Elite", group: "Backgrounds" },
    { key: "influence_underworld_specializations", prettyName: "Influence: Underworld", group: "Backgrounds" },
    { key: "ctdbs_merits", prettyName: "Merits", group: "Merits and Flaws" },
    { key: "ctdbs_flaws", prettyName: "Flaws", group: "Merits and Flaws" },
    ],
    textAttributes: [
    { key: "archetype", label: "Archetype" },
    { key: "ctdbs_kith", label: "Kith" },
    { key: "ctdbs_fealty_court", label: "Court" },
    { key: "ctdbs_noble_house", label: "House" },
    { key: "ctdbs_kith_group_type", label: "Group" },
    { key: "antecedence", label: "Primary, Secondary, or NPC" },
    ],
    sumCreationCategories: ["ctdbs_merits","ctdbs_flaws"],
  },
};
